import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tick-Tack-Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            {children}
        </body>
    </html>
  );
}
